sudo: required
services:
 - docker

before_install:
 - docker build -t asawin11/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true asawin11/react-test npm test

after_success:
 - docker build -t asawin11/multi-client ./client

